### ISSUE TITLE
Need sql query for driver’s current orders

### ISSUE THREAD

**Issue by jfk-sjsu** [jfk-sjsu/ODFDS#27]
We need to adjsut the sql query for driver.getOrders so it brings back orders assigned to a driver joined with the restaurant table info. In the end we need, for a given DriverID, the order(s) for that driver joined with the restaurant.Name, restaurant.Address, orders.CustName, orders.CustAddress, and orders.OrderID. Just need the sql query text, the rest can be adjusted.

**Comment by akshay-sud** [comment]
Try this out:

SELECT orders.OrderID, orders.OrderVal, orders.CustName, orders.CustAddr, orders.CustName, restaurant.RestName, restaurant.RestAddr FROM orders INNER JOIN restaurant ON orders.RestID=restaurant.RestID WHERE orders.DriverID=?;

**Comment by jfk-sjsu** [comment]
Will try thanks!
